name: floor
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.3.0
homepage: https://vitusortner.github.io/floor/
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  floor_annotation:
    path: ../floor_annotation/
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path_provider: ^2.0.11
  sqflite_common_ffi: ^2.1.1+1
  sqlite3_flutter_libs: ^0.5.7

dev_dependencies:
  build_runner: ^2.1.11
  collection: ^1.16.0
  floor_generator:
    path: ../floor_generator/
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
